### PR TITLE
Parser and tokenizer implemented

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #11

---

## PR-Codex overview
This PR adds necessary classes for working with Flatty, including tokens and entities.

### Detailed summary
- Added `ArrowToken` class
- Added `StringToken` class
- Added `Empty` class
- Added `Entity` class
- Added `Data` class
- Added package-info files for `tokens` and `entities` packages.

> The following files were skipped due to too many changes: `src/main/java/org/objectionary/entities/Data.java`, `src/main/java/org/objectionary/entities/Lambda.java`, `src/main/java/org/objectionary/entities/Locator.java`, `src/main/java/org/objectionary/tokens/BracketToken.java`, `src/main/java/org/objectionary/entities/FlatObject.java`, `src/main/java/org/objectionary/Tokenizer.java`, `src/main/java/org/objectionary/ObjectsBox.java`, `src/test/java/org/objectionary/ParsingTest.java`, `src/main/java/org/objectionary/entities/ObjectWithApplication.java`, `src/main/java/org/objectionary/Parser.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by EugeneDar** [comment]
998 linter errors, I will fix it later

**Comment by EugeneDar** [comment]
@yegor256 I've been trying for hours to solve the checkstyle problems, but there are still too many. I will have to postpone this activity for a while, unless you have another solution.

**Comment by yegor256** [comment]
@volodya-lombrozo please, review this one

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]
@EugeneDar I would highly recommend splitting that PR into several smaller PRs that are more logical and implement the task step by step. With this approach, we will be able to merge the entire solution much faster. Otherwise, we will spend a lot of time modifying the current PR. Please let me know if you will continue with that PR or create several smaller PRs.

**Comment by EugeneDar** [comment]
@yegor256 @volodya-lombrozo I will close this PR and create several smaller PRs.

**Pull request closed without merging**
