### PR TITLE
Readme implemented

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #57 

---

## PR-Codex overview
This PR adds usage instructions, installation steps, and examples to the README file of the Flatty repository. Additionally, it replaces mentions of the EO programming language with the phi-calculus language and removes a section on running tests.

### Detailed summary
- Adds a Quick Start section with usage instructions and code examples.
- Adds an Installation section with three steps to follow.
- Adds a Usage section with three steps to follow.
- Removes the Run Tests section.
- Adds an Examples section with a directory location to find nested objects.
- Updates the project description to refer to the phi-calculus language instead of the EO programming language.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur please, have a look

**Review by Graur — APPROVED** [review]
@EugeneDar Good one. Maybe we can add some badges to this project in future
@yegor256 Please have a look

**Comment by EugeneDar** [comment]
@yegor256 please, have a look

**Comment by EugeneDar** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
