### PR TITLE
Tests for entities reader created

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #49

---

## PR-Codex overview
This PR adds license headers to files and adds tests for the `Entities` class. 

### Detailed summary
- Adds MIT license header to files
- Adds tests for `Entities` class
- Implements `one()` and `nested()` methods in `Entities` class

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur please, have a look

**Comment by yegor256** [comment]
@EugeneDar check this: https://www.yegor256.com/2015/03/09/objects-end-with-er.html

**Comment by EugeneDar** [comment]
@yegor256 is this a mandatory change or is it my choice?

**Comment by EugeneDar** [comment]
@yegor256 It seems to me that if we write code that is going to be used/amended/rewritten by others in some way, we should rely on generally accepted patterns.

**Comment by yegor256** [comment]
@EugeneDar "generally accepted patterns" in OOP is what our entire project fights against :)

**Comment by EugeneDar** [comment]
@yegor256 ok, now you've convinced me

**Comment by EugeneDar** [comment]
@yegor256 please, have a look again

**Comment by yegor256** [comment]
@EugeneDar the name of a class must be a noun, not a verb. I would name this one "Entities" and the methods would be "one()" and "nested()"

**Comment by EugeneDar** [comment]
@yegor256 fixed, please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
