### PR TITLE
Skeleton created

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #3

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur I tried many solutions, but error didn't change. Maybe you had something similar and you know how to solve it?

**Comment by Graur** [comment]
@EugeneDar Let's remove windows build and create a new issue about it.

**Comment by EugeneDar** [comment]
@Graur I think it's something fundamental, and it's strange that it isn't working. But, sure, I will remove it.

**Comment by EugeneDar** [comment]
@Graur please, have a look

**Review by Graur — APPROVED** [review]
@EugeneDar Looks good! Please don't forget to create an issue about windows build

**Comment by EugeneDar** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@Graur please, review this one

**Comment by Graur** [comment]
@yegor256 I have already seen this pull request. It's just a template for the future improvements

**Comment by EugeneDar** [comment]
@yegor256, can you merge it?

**Comment by yegor256** [comment]
@EugeneDar I suggest you create `.rultor.yml` too, asap

**Comment by EugeneDar** [comment]
@yegor256 sure

**Comment by EugeneDar** [comment]
@yegor256 we already have `.rultor.yml`, correct me if I have misunderstood something.

**Comment by Graur** [comment]
@EugeneDar We need to invite [rultor](https://github.com/rultor) to this repository

**Pull request merged**
