### PR TITLE
Type checker methods implemented

### PR DESCRIPTION
**Pull request by EugeneDar**
Closes: #43
Closes: #44
Closes: #45
Closes: #46
Closes: #47

---

## PR-Codex overview
This PR adds implementation to the methods `isEmpty()`, `isLocator()`, `isData()`, `isLambda()`, and `isObject()` in the `TypeChecker` class. 

### Detailed summary
- Implementation added to `isEmpty()`, `isLocator()`, `isData()`, `isLambda()`, and `isObject()` methods in `TypeChecker` class. 
- `TypeCheckerTest` class test methods are no longer disabled. 
- Minor change in `README.md` file.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur please, have a look

**Review by Graur — APPROVED** [review]
@EugeneDar Well done
@yegor256 Could you please have a look

**Comment by Graur** [comment]
@EugeneDar Did you removed your `todo` puzzles?

**Comment by Graur** [comment]
@EugeneDar You linked this pull request with 5 puzzles. They should be closed automatically when you remove `todo` from your code in pull request. But there are no such changes in this pull request.

**Comment by EugeneDar** [comment]
@Graur

**Comment by Graur** [comment]
@EugeneDar So, you can remove `Closes: #number` from your first message

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
